# Sử dụng image cơ bản cho Node.js
FROM node:14

# Thiết lập thư mục làm việc
WORKDIR /app

# Sao chép các tệp package.json và package-lock.json vào thư mục làm việc
COPY package*.json ./

# Cài đặt các dependencies
RUN npm install

# Sao chép tất cả các tệp từ thư mục hiện tại vào thư mục làm việc
COPY . .

# Cổng mà ứng dụng Node.js sẽ lắng nghe
EXPOSE 8000

# Khởi động ứng dụng Node.js khi container được chạy
CMD ["node", "index.js"]
